name: pizzaparty
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/pizzaparty/assets/images/3786128removebgpreview1.png
    - packages/pizzaparty/assets/images/group.svg
    - packages/pizzaparty/assets/images/ellipse1.png
    - packages/pizzaparty/assets/images/arrow1.svg
    - packages/pizzaparty/assets/images/line1.svg
    - packages/pizzaparty/assets/images/ellipse2.png
    - packages/pizzaparty/assets/images/ellipse3.png
    - packages/pizzaparty/assets/images/arrow2.svg
    - packages/pizzaparty/assets/images/arrow3.svg
    - packages/pizzaparty/assets/images/ellipse6.png
    - packages/pizzaparty/assets/images/ellipse5.png
    - packages/pizzaparty/assets/images/ellipse4.png
    - packages/pizzaparty/assets/images/ellipse7.png
